"""add linked_account_id and linked_amount to goals

Revision ID: f03b5dbfbf8c
Revises: create_goals_table
Create Date: 2025-07-10 17:07:18.942490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03b5dbfbf8c'
down_revision = 'create_goals_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linked_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_index('ix_goals_category')
        batch_op.drop_index('ix_goals_status')
        batch_op.drop_index('ix_goals_user_id')
        batch_op.create_foreign_key('fk_goals_linked_account_id', 'accounts', ['linked_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goals_linked_account_id', type_='foreignkey')
        batch_op.create_index('ix_goals_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_goals_status', ['status'], unique=False)
        batch_op.create_index('ix_goals_category', ['category'], unique=False)
        batch_op.drop_column('linked_amount')
        batch_op.drop_column('linked_account_id')

    # ### end Alembic commands ###
